### PR TITLE
yarn to pnpm spike

### PR DESCRIPTION
**Pull request by RobbieTheWagner**

### CODE REVIEW

**Comment by chuckcarpenter** [comment]
renaming isn't going to be enough here, the basic commands don't work. e.g., 
image

**Comment by RobbieTheWagner** [comment]
> renaming isn't going to be enough here, the basic commands don't work. e.g., image

Yeah, I know renaming isn't the only thing we need. Stuff with docker needs to be done which I didn't do here as I don't know what to do there.

**Comment by chuckcarpenter** [comment]
@RobbieTheWagner way before docker is addressed the basic redwood commands don't work, e.g., `pnpm rw dev`

**Comment by chuckcarpenter** [comment]
No longer needed with #2846

**Pull request closed without merging**
