### PR TITLE
Add modal overlay opening x,y offset settings.

### PR DESCRIPTION
**Pull request by timodwhit**
Add the ability to offset the modal's overlay opening by an x,y value
for elements that are positioned uniquely on the screen. As an example:
This is useful for items that are placed inside an iframe that is in
a fixed position on the screen.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@timodwhit looks like we have a failing test here. Mind taking a look?

**Comment by rwwagner90** [comment]
@monshan would you be able to look into this?

**Comment by monshan** [comment]
@rwwagner90 fixed the tests and rebased with most recent shepherd, should be good to go

**Comment by rwwagner90** [comment]
Awesome, thanks @monshan!

**Comment by rwwagner90** [comment]
@monshan would it be possible to add some tests for these new options? I don't think new tests were added here right?

**Comment by monshan** [comment]
@rwwagner90 no tests added by Tim but sure I could write some that cover the feature, my first thought is some cypress that can offset in all 4 directions?

**Comment by rwwagner90** [comment]
@monshan yeah, that sounds perfect! Basically just testing at least a couple different values and making sure it moves.

**Comment by rwwagner90** [comment]
@monshan any updates on those tests? Would love to merge this soon 😄

**Comment by monshan** [comment]
@timodwhit 
Testing the feature will produce the following:
- Left: No offset, modal fills the window
- Right: X-axis offset 25px, modal fills window except for whitespace according to the offset in the bottom left

Can you confirm that this is the desired behavior? Not that the modal offset will remain the same size as the window with adjusted positioning?

Screen Shot 2022-06-22 at 10 46 13 AM

**Comment by timodwhit** [comment]
@monshan I'm sorry. I'm not sure I understand the question or the use case.

**Comment by EmNicholson93** [comment]
@timodwhit @monshan is this issue resolved or are there still lingering questions regarding the tests for this feature?

**Comment by DerekJarvis** [comment]
> @timodwhit @monshan is this issue resolved or are there still lingering questions regarding the tests for this feature?

I believe @monshan asked a question about the purpose of the PR and was awaiting a response. I found this PR because I was looking for this exact feature. I believe the purpose of this feature is to allow the overlay SVG that is generated to offset from the target element. This is useful in cases where the current CSS does not have margins around them and the overlay is very tight. It allows Shepherd to generate a better looking overlay without needing to rework the website's CSS.

**Comment by timodwhit** [comment]
Sorry for the delay in the response and the long gap. 

Yes, @monshan I believe your tests are correct.

**Comment by chuckcarpenter** [comment]
This looks to have been added and handled in #2551

**Pull request closed without merging**
